server:
  port: ${APPLICATION_PORT:9090}

spring:
  application:
    name: ppai


  datasource:
    url: jdbc:mariadb://localhost:3306/ppai
    username: root
    password: admin123
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
